name: Push apisix to Docker image
on:
  push:
    branches: ['release/apisix-**']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username=${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push apisix image to Docker Hub
        run: |
          make push-multiarch-on-alpine
          make build-on-centos
          make push-on-centos
